server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      # defaultZone: http://peer2:8769/eureka/
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false  # 注册中心职责是维护服务实例，false：不检索服务。
    register-with-eureka: false # 此应用为注册中心，false：不向注册中心注册自己。

management:
  endpoints:
    web:
      exposure:
        include: "*"
