/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.domain.tables.Customer;
import org.jooq.domain.tables.SysGroup;
import org.jooq.domain.tables.SysLog;
import org.jooq.domain.tables.SysOrganization;
import org.jooq.domain.tables.SysResource;
import org.jooq.domain.tables.SysRole;
import org.jooq.domain.tables.SysUser;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>springboot_demo</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMER_PRIMARY = Indexes0.CUSTOMER_PRIMARY;
    public static final Index SYS_GROUP_PRIMARY = Indexes0.SYS_GROUP_PRIMARY;
    public static final Index SYS_LOG_PRIMARY = Indexes0.SYS_LOG_PRIMARY;
    public static final Index SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_ID = Indexes0.SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_ID;
    public static final Index SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_IDS = Indexes0.SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_IDS;
    public static final Index SYS_ORGANIZATION_PRIMARY = Indexes0.SYS_ORGANIZATION_PRIMARY;
    public static final Index SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_ID = Indexes0.SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_ID;
    public static final Index SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_IDS = Indexes0.SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_IDS;
    public static final Index SYS_RESOURCE_PRIMARY = Indexes0.SYS_RESOURCE_PRIMARY;
    public static final Index SYS_ROLE_IDX_SYS_ROLE_RESOURCE_IDS = Indexes0.SYS_ROLE_IDX_SYS_ROLE_RESOURCE_IDS;
    public static final Index SYS_ROLE_PRIMARY = Indexes0.SYS_ROLE_PRIMARY;
    public static final Index SYS_USER_IDX_SYS_USER_ORGANIZATION_ID = Indexes0.SYS_USER_IDX_SYS_USER_ORGANIZATION_ID;
    public static final Index SYS_USER_IDX_SYS_USER_USERNAME = Indexes0.SYS_USER_IDX_SYS_USER_USERNAME;
    public static final Index SYS_USER_PRIMARY = Indexes0.SYS_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMER_PRIMARY = Internal.createIndex("PRIMARY", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index SYS_GROUP_PRIMARY = Internal.createIndex("PRIMARY", SysGroup.SYS_GROUP, new OrderField[] { SysGroup.SYS_GROUP.ID }, true);
        public static Index SYS_LOG_PRIMARY = Internal.createIndex("PRIMARY", SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.ID }, true);
        public static Index SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_ID = Internal.createIndex("idx_sys_organization_parent_id", SysOrganization.SYS_ORGANIZATION, new OrderField[] { SysOrganization.SYS_ORGANIZATION.PARENT_ID }, false);
        public static Index SYS_ORGANIZATION_IDX_SYS_ORGANIZATION_PARENT_IDS = Internal.createIndex("idx_sys_organization_parent_ids", SysOrganization.SYS_ORGANIZATION, new OrderField[] { SysOrganization.SYS_ORGANIZATION.PARENT_IDS }, false);
        public static Index SYS_ORGANIZATION_PRIMARY = Internal.createIndex("PRIMARY", SysOrganization.SYS_ORGANIZATION, new OrderField[] { SysOrganization.SYS_ORGANIZATION.ID }, true);
        public static Index SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_ID = Internal.createIndex("idx_sys_resource_parent_id", SysResource.SYS_RESOURCE, new OrderField[] { SysResource.SYS_RESOURCE.PARENT_ID }, false);
        public static Index SYS_RESOURCE_IDX_SYS_RESOURCE_PARENT_IDS = Internal.createIndex("idx_sys_resource_parent_ids", SysResource.SYS_RESOURCE, new OrderField[] { SysResource.SYS_RESOURCE.PARENT_IDS }, false);
        public static Index SYS_RESOURCE_PRIMARY = Internal.createIndex("PRIMARY", SysResource.SYS_RESOURCE, new OrderField[] { SysResource.SYS_RESOURCE.ID }, true);
        public static Index SYS_ROLE_IDX_SYS_ROLE_RESOURCE_IDS = Internal.createIndex("idx_sys_role_resource_ids", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.RESOURCE_IDS }, false);
        public static Index SYS_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ID }, true);
        public static Index SYS_USER_IDX_SYS_USER_ORGANIZATION_ID = Internal.createIndex("idx_sys_user_organization_id", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.ORGANIZATION_ID }, false);
        public static Index SYS_USER_IDX_SYS_USER_USERNAME = Internal.createIndex("idx_sys_user_username", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USERNAME }, true);
        public static Index SYS_USER_PRIMARY = Internal.createIndex("PRIMARY", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.ID }, true);
    }
}
