/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain;


import javax.annotation.Generated;

import org.jooq.domain.tables.Customer;
import org.jooq.domain.tables.SysGroup;
import org.jooq.domain.tables.SysLog;
import org.jooq.domain.tables.SysOrganization;
import org.jooq.domain.tables.SysResource;
import org.jooq.domain.tables.SysRole;
import org.jooq.domain.tables.SysUser;


/**
 * Convenience access to all tables in springboot_demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 客户信息表
     */
    public static final Customer CUSTOMER = org.jooq.domain.tables.Customer.CUSTOMER;

    /**
     * 用户组表
     */
    public static final SysGroup SYS_GROUP = org.jooq.domain.tables.SysGroup.SYS_GROUP;

    /**
     * 系统日志表
     */
    public static final SysLog SYS_LOG = org.jooq.domain.tables.SysLog.SYS_LOG;

    /**
     * 组织机构表
     */
    public static final SysOrganization SYS_ORGANIZATION = org.jooq.domain.tables.SysOrganization.SYS_ORGANIZATION;

    /**
     * 资源表
     */
    public static final SysResource SYS_RESOURCE = org.jooq.domain.tables.SysResource.SYS_RESOURCE;

    /**
     * 角色表
     */
    public static final SysRole SYS_ROLE = org.jooq.domain.tables.SysRole.SYS_ROLE;

    /**
     * 用户表
     */
    public static final SysUser SYS_USER = org.jooq.domain.tables.SysUser.SYS_USER;
}
