/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.domain.tables.SysLog;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLogRecord extends UpdatableRecordImpl<SysLogRecord> implements Record12<Long, String, String, String, String, String, Long, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 583324467;

    /**
     * Setter for <code>springboot_demo.sys_log.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.ip</code>. 用户ip
     */
    public void setIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.ip</code>. 用户ip
     */
    public String getIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.req_method</code>. 请求方法
     */
    public void setReqMethod(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.req_method</code>. 请求方法
     */
    public String getReqMethod() {
        return (String) get(3);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.req_uri</code>. 请求URL
     */
    public void setReqUri(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.req_uri</code>. 请求URL
     */
    public String getReqUri() {
        return (String) get(4);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.exec_method</code>. 执行方法
     */
    public void setExecMethod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.exec_method</code>. 执行方法
     */
    public String getExecMethod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.exec_time</code>. 响应时间
     */
    public void setExecTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.exec_time</code>. 响应时间
     */
    public Long getExecTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.args</code>. 参数
     */
    public void setArgs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.args</code>. 参数
     */
    public String getArgs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.return_val</code>. 返回值
     */
    public void setReturnVal(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.return_val</code>. 返回值
     */
    public String getReturnVal() {
        return (String) get(8);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.exec_desc</code>. 描述
     */
    public void setExecDesc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.exec_desc</code>. 描述
     */
    public String getExecDesc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.status</code>. 状态
     */
    public void setStatus(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.status</code>. 状态
     */
    public String getStatus() {
        return (String) get(10);
    }

    /**
     * Setter for <code>springboot_demo.sys_log.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_log.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Long, String, String, String, String, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Long, String, String, String, String, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysLog.SYS_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysLog.SYS_LOG.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysLog.SYS_LOG.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysLog.SYS_LOG.REQ_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysLog.SYS_LOG.REQ_URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysLog.SYS_LOG.EXEC_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return SysLog.SYS_LOG.EXEC_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SysLog.SYS_LOG.ARGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysLog.SYS_LOG.RETURN_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SysLog.SYS_LOG.EXEC_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SysLog.SYS_LOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return SysLog.SYS_LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReqMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getReqUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getExecMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getExecTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getArgs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getReturnVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getExecDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReqMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReqUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getExecMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getExecTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getArgs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getReturnVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getExecDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value3(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value4(String value) {
        setReqMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value5(String value) {
        setReqUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value6(String value) {
        setExecMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value7(Long value) {
        setExecTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value8(String value) {
        setArgs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value9(String value) {
        setReturnVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value10(String value) {
        setExecDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value11(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord value12(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysLogRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7, String value8, String value9, String value10, String value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysLogRecord
     */
    public SysLogRecord() {
        super(SysLog.SYS_LOG);
    }

    /**
     * Create a detached, initialised SysLogRecord
     */
    public SysLogRecord(Long id, String username, String ip, String reqMethod, String reqUri, String execMethod, Long execTime, String args, String returnVal, String execDesc, String status, Timestamp createTime) {
        super(SysLog.SYS_LOG);

        set(0, id);
        set(1, username);
        set(2, ip);
        set(3, reqMethod);
        set(4, reqUri);
        set(5, execMethod);
        set(6, execTime);
        set(7, args);
        set(8, returnVal);
        set(9, execDesc);
        set(10, status);
        set(11, createTime);
    }
}
