/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.domain.tables.SysRole;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleRecord extends UpdatableRecordImpl<SysRoleRecord> implements Record5<Long, String, String, String, Byte> {

    private static final long serialVersionUID = 2058850969;

    /**
     * Setter for <code>springboot_demo.sys_role.id</code>. 编号
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_role.id</code>. 编号
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>springboot_demo.sys_role.role</code>. 角色名
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_role.role</code>. 角色名
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>springboot_demo.sys_role.description</code>. 描述
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_role.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>springboot_demo.sys_role.resource_ids</code>. 资源编号列表
     */
    public void setResourceIds(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_role.resource_ids</code>. 资源编号列表
     */
    public String getResourceIds() {
        return (String) get(3);
    }

    /**
     * Setter for <code>springboot_demo.sys_role.available</code>. 是否有效
     */
    public void setAvailable(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_role.available</code>. 是否有效
     */
    public Byte getAvailable() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysRole.SYS_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysRole.SYS_ROLE.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysRole.SYS_ROLE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysRole.SYS_ROLE.RESOURCE_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return SysRole.SYS_ROLE.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getResourceIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getResourceIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value2(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value4(String value) {
        setResourceIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord value5(Byte value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysRoleRecord values(Long value1, String value2, String value3, String value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysRoleRecord
     */
    public SysRoleRecord() {
        super(SysRole.SYS_ROLE);
    }

    /**
     * Create a detached, initialised SysRoleRecord
     */
    public SysRoleRecord(Long id, String role, String description, String resourceIds, Byte available) {
        super(SysRole.SYS_ROLE);

        set(0, id);
        set(1, role);
        set(2, description);
        set(3, resourceIds);
        set(4, available);
    }
}
