/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.domain.tables.SysResource;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 资源表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysResourceRecord extends UpdatableRecordImpl<SysResourceRecord> implements Record11<Long, String, String, String, Long, String, String, Byte, String, Integer, Byte> {

    private static final long serialVersionUID = 810920765;

    /**
     * Setter for <code>springboot_demo.sys_resource.id</code>. 编号
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.id</code>. 编号
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.type</code>. 资源类型
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.type</code>. 资源类型
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.url</code>. 链接地址
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.url</code>. 链接地址
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.parent_id</code>. 父编号
     */
    public void setParentId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.parent_id</code>. 父编号
     */
    public Long getParentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.parent_ids</code>. 父编号列表
     */
    public void setParentIds(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.parent_ids</code>. 父编号列表
     */
    public String getParentIds() {
        return (String) get(5);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.permission</code>. 权限字符串
     */
    public void setPermission(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.permission</code>. 权限字符串
     */
    public String getPermission() {
        return (String) get(6);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.available</code>. 是否有效
     */
    public void setAvailable(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.available</code>. 是否有效
     */
    public Byte getAvailable() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.icon</code>. 图标
     */
    public void setIcon(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.icon</code>. 图标
     */
    public String getIcon() {
        return (String) get(8);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.priority</code>. 优先级
     */
    public void setPriority(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.priority</code>. 优先级
     */
    public Integer getPriority() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>springboot_demo.sys_resource.leaf</code>. 叶子节点
     */
    public void setLeaf(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_resource.leaf</code>. 叶子节点
     */
    public Byte getLeaf() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, Long, String, String, Byte, String, Integer, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, Long, String, String, Byte, String, Integer, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysResource.SYS_RESOURCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysResource.SYS_RESOURCE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysResource.SYS_RESOURCE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysResource.SYS_RESOURCE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SysResource.SYS_RESOURCE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysResource.SYS_RESOURCE.PARENT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysResource.SYS_RESOURCE.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return SysResource.SYS_RESOURCE.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SysResource.SYS_RESOURCE.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return SysResource.SYS_RESOURCE.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return SysResource.SYS_RESOURCE.LEAF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component11() {
        return getLeaf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getParentIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getLeaf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value5(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value6(String value) {
        setParentIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value7(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value8(Byte value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value9(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value10(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord value11(Byte value) {
        setLeaf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysResourceRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, String value7, Byte value8, String value9, Integer value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysResourceRecord
     */
    public SysResourceRecord() {
        super(SysResource.SYS_RESOURCE);
    }

    /**
     * Create a detached, initialised SysResourceRecord
     */
    public SysResourceRecord(Long id, String name, String type, String url, Long parentId, String parentIds, String permission, Byte available, String icon, Integer priority, Byte leaf) {
        super(SysResource.SYS_RESOURCE);

        set(0, id);
        set(1, name);
        set(2, type);
        set(3, url);
        set(4, parentId);
        set(5, parentIds);
        set(6, permission);
        set(7, available);
        set(8, icon);
        set(9, priority);
        set(10, leaf);
    }
}
