/*
 * This file is generated by jOOQ.
 */
package org.jooq.domain.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.domain.tables.SysUser;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRecord extends UpdatableRecordImpl<SysUserRecord> implements Record8<Long, Long, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = 516200465;

    /**
     * Setter for <code>springboot_demo.sys_user.id</code>. 编号
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.id</code>. 编号
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.organization_id</code>. 组织机构编号
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.organization_id</code>. 组织机构编号
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.salt</code>. 盐值
     */
    public void setSalt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.salt</code>. 盐值
     */
    public String getSalt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.role_ids</code>. 角色列表
     */
    public void setRoleIds(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.role_ids</code>. 角色列表
     */
    public String getRoleIds() {
        return (String) get(5);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.group_ids</code>. 组列表
     */
    public void setGroupIds(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.group_ids</code>. 组列表
     */
    public String getGroupIds() {
        return (String) get(6);
    }

    /**
     * Setter for <code>springboot_demo.sys_user.locked</code>. 是否锁定
     */
    public void setLocked(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>springboot_demo.sys_user.locked</code>. 是否锁定
     */
    public Byte getLocked() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, String, String, String, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, String, String, String, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysUser.SYS_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SysUser.SYS_USER.ORGANIZATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysUser.SYS_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysUser.SYS_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysUser.SYS_USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SysUser.SYS_USER.ROLE_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysUser.SYS_USER.GROUP_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return SysUser.SYS_USER.LOCKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRoleIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getGroupIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getLocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOrganizationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRoleIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getGroupIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getLocked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value5(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value6(String value) {
        setRoleIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value7(String value) {
        setGroupIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord value8(Byte value) {
        setLocked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, Byte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysUserRecord
     */
    public SysUserRecord() {
        super(SysUser.SYS_USER);
    }

    /**
     * Create a detached, initialised SysUserRecord
     */
    public SysUserRecord(Long id, Long organizationId, String username, String password, String salt, String roleIds, String groupIds, Byte locked) {
        super(SysUser.SYS_USER);

        set(0, id);
        set(1, organizationId);
        set(2, username);
        set(3, password);
        set(4, salt);
        set(5, roleIds);
        set(6, groupIds);
        set(7, locked);
    }
}
